/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    AInput: typeof import('ant-design-vue/lib')['Input']
    DefaultHeader: typeof import('./components/DefaultHeader.vue')['default']
    DefaultLoad: typeof import('./components/DefaultLoad.vue')['default']
    Inbox: typeof import('./components/Inbox.vue')['default']
    MailBox: typeof import('./components/MailBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedInput: typeof import('./components/SharedInput.vue')['default']
    UndoOutlined: typeof import('@ant-design/icons-vue')['UndoOutlined']
  }
}
